### PR TITLE
[NEXUS-14940] Deprecate service/siesta

### PR DESCRIPTION
**Pull request by bradbeck**
https://issues.sonatype.org/browse/NEXUS-14940
Related PR: https://github.com/sonatype/nexus-internal/pull/2672

### CODE REVIEW

**Review by ataylor284 — APPROVED** [review]
+1

**Review by collinpeters — APPROVED** [review]
+1

**Comment by bradbeck** [comment]
Will hold off merging this until the NXRM 3 changes are released and the corresponding doc changes are published.

**Comment by zeitounator** [comment]
Hi. Do any of you know a potential release date for nexus 3.7 and if any public RC will be available before the release ? We have an ansible role installing nexus and actively using the rest api through groovy scripts for provisioning. I'd like to make changes early and test them to make sure we are ready. Any info appreciated.

**Comment by bradbeck** [comment]
At this point in time, this change will not be included in a 3.7.0 release.

**Comment by bradbeck** [comment]
`@Grab` references in the groovy scripts will need to be updated to reflect the correct version once the associated NXRM changes have been released.

**Comment by zeitounator** [comment]
@bradbeck: thanks for te info.

**Pull request merged**
