### PR TITLE
[NEXUS-9362] Rename 'Sonatype Nexus' to 'Nexus Repository Manager'

### PR DESCRIPTION
**Pull request by djsauble**
Issue: https://issues.sonatype.org/browse/NEXUS-9362

### CODE REVIEW

**Comment by mosabua** [comment]
+1 .. if you are doing that change you and the book change (eval guide) you will also have to figure out how the bundle is created now and update that. I dont know where that is now. Used to be in the nexus-bundles project but I am not sure if that is still alive or if it got collapsed into the internal repo or so. Check with @jdillon or @mcculls

**Comment by djsauble** [comment]
@jdillon Can you shed any light on how the bundle is created? I’m happy to do that, just need some pointers.

**Comment by jdillon** [comment]
@djsauble manfred is talking about the bundle assemblies here: https://github.com/sonatype/nexus-internal/tree/master/private/assemblies ... ie. the official product distribution bundle assemblies.

**Comment by mosabua** [comment]
@djsauble if you want to do that.. let me know as there are some gotchas to it. Or otherwise I can do it once this is merged and the book is also updated.

**Comment by kellyrob99** [comment]
+1

**Pull request closed without merging**
