### PR TITLE
[NEXUS-11214] Updated groovy script, pom version exact number

### PR DESCRIPTION
**Pull request by dulanism**
For 3.1 release
JIRA: https://issues.sonatype.org/browse/NEXUS-11214

NOTE: wait to merge till launched and sync'd to Central

### CODE REVIEW

**Comment by joedragons** [comment]
Maybe unrelated but will https://github.com/sonatype/nexus-book-examples/blob/nexus-3.0.x/scripting/README.asciidoc need updated?  I see it says 3.0.

**Comment by joedragons** [comment]
+1 besides above Q (maybe unrelated).  I reviewed all the files to make sure none slipped thru as well as the (simple) review, thanks!

**Comment by mosabua** [comment]
lgtm but we can only push this once all the bits are in central and we have verified this. So we have to wait for that to be done fyi @mrprescott @kellyrob99

**Comment by mosabua** [comment]
@joedragons I fixed that link

**Comment by joedragons** [comment]
@mosabua ty sir=)

**Comment by mosabua** [comment]
Files are in central... e.g.  http://repo1.maven.org/maven2/org/sonatype/nexus/nexus-rest-client/3.1.0-04/

So you can test it now and merge it after @dulanism

**Comment by mosabua** [comment]
Should we merge, test, rename branches and so on @dulanism ... I can do that now if you want.

**Pull request merged**
