### PR TITLE
Updated temporary version ahead of release

### PR DESCRIPTION
**Pull request by dulanism**
JIRA: https://issues.sonatype.org/browse/NEXUS-10404
Changed 3.0.0-03 to 3.0.1-01
(Note: version subject to change)

### CODE REVIEW

**Comment by mosabua** [comment]
There should be some Maven pom references that need to be updated as well

**Comment by dulanism** [comment]
Getting a head start; versions will likely change

**Comment by dulanism** [comment]
Are there any other updates overlooked? @mosabua

**Comment by mosabua** [comment]
None that I am aware of without looking ;-)

**Comment by joedragons** [comment]
+1

**Pull request merged**
